In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split

In [31]:
digits=load_digits()


In [32]:
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)


In [33]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9574074074074074

In [34]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.35

In [35]:
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)
rfc.score(X_test,y_test)

0.9611111111111111

In [36]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [37]:
#example

for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [38]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [39]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.35

In [40]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

0.9574074074074074

In [41]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9481481481481482

In [13]:
from sklearn.model_selection import StratifiedKFold
folds =StratifiedKFold(n_splits=3)

In [14]:
scores_l=[]
scores_svm=[]
scores_rfc=[]

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
                                  digits.target[train_index],digits.target[test_index]
     
    scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test)) 
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rfc.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))    

In [15]:
scores_l,scores_svm,scores_rfc

([0.8964941569282137, 0.9515859766277128, 0.9115191986644408],
 [0.41068447412353926, 0.41569282136894825, 0.4273789649415693],
 [0.9332220367278798, 0.9449081803005008, 0.9282136894824707])

Another simple way

In [16]:
from sklearn.model_selection import cross_val_score

In [17]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

array([0.89534884, 0.94991653, 0.90939597])

In [18]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.39368771, 0.41068447, 0.45973154])

In [19]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.92524917, 0.94490818, 0.91275168])

# Exercise

In [21]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [22]:
iris  = load_iris()

# Logistic regression

In [24]:
l_score = cross_val_score(LogisticRegression(),iris.data,iris.target)
l_score

array([0.96078431, 0.92156863, 0.95833333])

In [25]:
np.average(l_score)

0.9468954248366014

# SVM

In [26]:
s_score = cross_val_score(SVC(),iris.data,iris.target)
s_score

array([0.98039216, 0.96078431, 0.97916667])

In [27]:
np.average(s_score)

0.9734477124183006

# Random forest

In [28]:
r_scores=cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target)
r_scores

array([0.98039216, 0.94117647, 1.        ])

In [29]:
np.average(r_scores)

0.9738562091503268