In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split

In [9]:
digits=load_digits()


In [41]:
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)


In [42]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9592592592592593

In [43]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.3962962962962963

In [44]:
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)
rfc.score(X_test,y_test)

0.9537037037037037

In [45]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [46]:
#example

for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [47]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [48]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.3962962962962963

In [49]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

0.9592592592592593

In [50]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9574074074074074

In [52]:
from sklearn.model_selection import StratifiedKFold
folds =StratifiedKFold(n_splits=3)

In [68]:
scores_l=[]
scores_svm=[]
scores_rfc=[]

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
                                  digits.target[train_index],digits.target[test_index]
     
    scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test)) 
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rfc.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))    

In [61]:
scores_l,scores_svm,scores_rfc

([0.8964941569282137, 0.9515859766277128, 0.9115191986644408],
 [0.41068447412353926, 0.41569282136894825, 0.4273789649415693],
 [0.9382303839732888, 0.9449081803005008, 0.9198664440734557])

Another simple way

In [62]:
from sklearn.model_selection import cross_val_score

In [63]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

array([0.89534884, 0.94991653, 0.90939597])

In [64]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.39368771, 0.41068447, 0.45973154])

In [66]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93355482, 0.93656093, 0.93120805])