In [1]:
import pandas as pd
df=pd.read_csv("titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [2]:
df.drop(["PassengerId","Name","SibSp","Parch","Cabin","Embarked"],axis='columns',inplace=True)
df.head()

Survived  Pclass     Sex   Age            Ticket     Fare
0         0       3    male  22.0         A/5 21171   7.2500
1         1       1  female  38.0          PC 17599  71.2833
2         1       3  female  26.0  STON/O2. 3101282   7.9250
3         1       1  female  35.0            113803  53.1000
4         0       3    male  35.0            373450   8.0500

In [3]:
target=df.Survived
inputs=df.drop("Survived",axis=1)

In [4]:
dummies=pd.get_dummies(inputs.Sex)
dummies.head(2)

female  male
0       0     1
1       1     0

In [5]:
inputs =pd.concat([inputs,dummies],axis=1)
inputs.head(3)

Pclass     Sex   Age            Ticket     Fare  female  male
0       3    male  22.0         A/5 21171   7.2500       0     1
1       1  female  38.0          PC 17599  71.2833       1     0
2       3  female  26.0  STON/O2. 3101282   7.9250       1     0

In [6]:
inputs.drop(["Sex","Ticket"],axis=1,inplace=True)
inputs.head(3)

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0

In [7]:
inputs.isnull().sum()

Pclass      0
Age       177
Fare        0
female      0
male        0
dtype: int64

In [8]:
inputs.shape

(891, 5)

In [9]:
inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs.head(6)

Pclass        Age     Fare  female  male
0       3  22.000000   7.2500       0     1
1       1  38.000000  71.2833       1     0
2       3  26.000000   7.9250       1     0
3       1  35.000000  53.1000       1     0
4       3  35.000000   8.0500       0     1
5       3  29.699118   8.4583       0     1

In [10]:
inputs.isnull().sum()

Pclass    0
Age       0
Fare      0
female    0
male      0
dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target, test_size=0.2)

In [12]:
len(X_train)

712

In [13]:
len(X_test)

179

In [14]:
len(inputs)

891

In [15]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [16]:
model.fit(X_train, y_train)

GaussianNB(priors=None)

In [17]:
model.score(X_test,y_test)

0.770949720670391

In [18]:
X_test[:10]

Pclass        Age      Fare  female  male
390       1  36.000000  120.0000       0     1
438       1  64.000000  263.0000       0     1
734       2  23.000000   13.0000       0     1
112       3  22.000000    8.0500       0     1
154       3  29.699118    7.3125       0     1
256       1  29.699118   79.2000       1     0
663       3  36.000000    7.4958       0     1
690       1  31.000000   57.0000       0     1
431       3  29.699118   16.1000       1     0
729       3  25.000000    7.9250       1     0

In [19]:
y_test[:10]

390    1
438    0
734    0
112    0
154    0
256    1
663    0
690    1
431    1
729    0
Name: Survived, dtype: int64

In [20]:
model.predict(X_test[:10])

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 1], dtype=int64)

In [21]:
model.predict_proba(X_test[:10])

array([[1.80681094e-01, 8.19318906e-01],
       [2.65317005e-10, 1.00000000e+00],
       [9.78474216e-01, 2.15257843e-02],
       [9.88849407e-01, 1.11505926e-02],
       [9.89985191e-01, 1.00148088e-02],
       [1.75476404e-03, 9.98245236e-01],
       [9.90340751e-01, 9.65924947e-03],
       [8.92475636e-01, 1.07524364e-01],
       [5.21602920e-02, 9.47839708e-01],
       [4.80578650e-02, 9.51942135e-01]])

# Email Spam Detection

In [22]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/14_naive_bayes/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [23]:
df.groupby("Category").describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [24]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam,test_size=0.2)

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
from sklearn.naive_bayes import MultinomialNB
model= MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [36]:
emails=[
       "Your free ringtone is waiting to be collected. Simply text the password ""MIX"" to 85069 to verify. Get Usher and Britney. FML, PO Box 5249, MK17 92H. 450Ppw 16",
       "Watching telugu movie..wat abt u?"
]
emails_count=v.transform(emails)
model.predict(emails_count)

array([1, 0], dtype=int64)

In [37]:
X_test_count=v.transform(X_test)
model.score(X_test_count,y_test)

0.9865470852017937

In [43]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [44]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
     steps=[('vectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)), ('nb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [45]:
clf.score(X_test,y_test)

0.9865470852017937

In [46]:
clf.predict(emails)

array([1, 0], dtype=int64)

In [47]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

C:\Users\anike\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [57]:
rfc.fit(X_train_count,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [58]:
rfc.score(X_test_count,y_test)

0.9748878923766816